version: "3"
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - list-db:/backend/instance
    ports:
      - "5000:5000"
volumes:
  list-db: